---
- name: Prepare k3s nodes
  hosts: k3s_cluster
  gather_facts: yes
  become: true
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi

- name: Setup k3s servers
  hosts: master
  roles:
    - role: k3s/server
      become: true

- name: Setup k3s agents
  hosts: node
  become: true
  roles:
    - role: k3s/agent

- name: Configure k3s cluster
  hosts: master
  become: true
  roles:
    - role: server_post